### ISSUE TITLE
use with react-hook-form

### ISSUE THREAD

**Issue by dev01udu** [iamchathu/react-material-file-upload#2]
Hey, bud There's an example of how can I use it with react-hook-form?

**Comment by iamchathu** [comment]
@dev01udu yes, 

[codesandbox](https://codesandbox.io/s/react-material-file-upload-t156i)

**Comment by iamchathu** [comment]
Opps. Sorry I will add it today.

**Comment by iamchathu** [comment]
@dev01udu [CodeSandBox](https://codesandbox.io/s/react-material-file-upload-with-react-hook-form-2dh1v4?file=/src/components/my-from.tsx)

**Comment by dev01udu** [comment]
thank chathu it was a looking for you are the best.

**Comment by nikedinviz** [comment]
how to preview the uploaded file?
